name: Pytest
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.9']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x86
      - name: Python Dependencies Install
        run: |
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

    - name: Test with pytest
      run: |
        pytest -s --verbose
