name: Main Testing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - ready_for_review
      - review_requested

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.9']
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x86
      - name: Python Dependencies Install
        run: |
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Test with pytest
        run: |
          pytest -s --verbose
